### ISSUE TITLE
Include example bcl2fastq folder or dataset

### ISSUE THREAD

**Issue by sujaikumar** [bartongroup/AlmostSignificant#2]
Would it be possible to add an example input bcl2fastq tar gz directory either to this repo or to some other location? I would like to test the software to recommend it to sequencing centres or to tell seq centres that they should give us the whole folder when we do large projects, but I don't have access to any bcl2fastq output right now.

**Comment by iosefward** [comment]
I'd love to do this, but I'm going to have to work out how. I'll have to find a sequencing run that's either all public data, or a run which I can remove any non-public data from. It'll not be small regardless. I'll see what I can do and get back to you.

**Comment by drchriscole** [comment]
Hi Sujai,

Many thanks for the comment. This is something we have considered including and have looked at it again for you.

Unfortunately we don't have any to runs where all the data is now public and/or published which makes distributing it tricky as we would either need to obfuscate it somehow or remove unreleasable samples. All of this would be a very manual process and error-prone. More likely to cause problems than to solve them.

An alternative is to take one of the Illumina public datasets which are made available via BaseSpace. Downloading anything other than fastqs is not feasible, unfortunately.

We are open to other suggestions, but at this point we aren't able to provide this.

**Comment by sujaikumar** [comment]
Got it. Thanks. Didn't think of privacy issue.
